version: '3.8'

services:
  database:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhook-multiplexer
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webhook-multiplexer
      - DB_HOST=database
      - DB_PORT=5432
